@extends('layout')
@section('title','Administration')
@section('content')
<div class="page-head"><div><div class="eyebrow">BRUGERE OG ADGANG</div><h1>Administration</h1><p>Hold styr på medarbejdere, roller og første login.</p></div><a class="btn" href="/administration/medarbejder">＋ Opret medarbejder</a></div>
<div class="actions" style="margin-bottom:24px"><a class="btn secondary" href="/viden/administration">Indhold og mapper</a><a class="btn secondary" href="/kompetencer">Kompetencematrix</a><a class="btn secondary" href="/katalog">Kompetencer og kursuskatalog</a></div><div class="grid three"><div class="card"><div class="eyebrow">AKTIVE MEDARBEJDERE</div><h2 style="font-size:32px;margin:0">{{ $people->where('active',true)->count() }}</h2></div><div class="card"><div class="eyebrow">FØRSTE LOGIN GENNEMFØRT</div><h2 style="font-size:32px;margin:0">{{ $people->where('active',true)->whereNotNull('first_login_at')->count() }}</h2></div><div class="card"><div class="eyebrow">IKKE KOMMET I GANG</div><h2 style="font-size:32px;margin:0">{{ $people->where('active',true)->whereNull('first_login_at')->count() }}</h2></div></div>
<div class="section-head"><h2>Medarbejdere</h2><a class="btn secondary small" href="/administration/adgang.csv">Hent adgangsoversigt · CSV ↓</a></div>
<div class="table-wrap"><table><thead><tr><th>Medarbejder</th><th>Roller</th><th>Kontostatus</th><th>Første login</th><th>Seneste login</th><th><span class="muted">Handling</span></th></tr></thead><tbody>@foreach($people as $person)<tr><td><span class="person-name">{{ $person->name }}</span><small>{{ $person->email }}</small></td><td><small>Medarbejder{{ $person->is_leader ? ' · Leder':'' }}{{ $person->is_admin ? ' · Administrator':'' }}</small></td><td><span class="pill {{ !$person->active ? 'inactive' : (!$person->first_login_at ? 'waiting':'') }}">{{ !$person->active ? 'Deaktiveret' : (!$person->first_login_at ? 'Ikke kommet i gang':'Aktiv') }}</span></td><td>{{ $person->first_login_at ? \App\Support\DateFormat::dateTime($person->first_login_at) : 'Ikke logget ind' }}</td><td>{{ \App\Support\DateFormat::dateTime($person->last_login_at) }}</td><td><a class="btn secondary small" href="/administration/medarbejder/{{ $person->id }}">Redigér</a></td></tr>@endforeach</tbody></table></div>
<p class="notice">Adgang tildelt og første login er forskellige oplysninger. Oversigten viser registreret adgang og login, ikke om materialet er læst eller forstået.</p>
<div class="section-head"><h2>Seneste administrationsændringer</h2></div><div class="table-wrap"><table><thead><tr><th>Tidspunkt</th><th>Handling</th><th>Aktør</th><th>Reference</th></tr></thead><tbody>@forelse($events as $event)<tr><td>{{ \App\Support\DateFormat::dateTime($event->created_at) }}</td><td>{{ ['user_created'=>'Medarbejder oprettet','user_updated'=>'Medarbejder ændret','reference_uploaded'=>'Privat referencefil gemt','access_exported'=>'Adgangsoversigt eksporteret'][$event->event] ?? $event->event }}</td><td>{{ $event->actor ?? 'System' }}</td><td>{{ $event->subject_type }} {{ $event->subject_id }}</td></tr>@empty<tr><td colspan="4">Ingen ændringer registreret endnu.</td></tr>@endforelse</tbody></table></div>
@endsection

