@extends('layout')
@section('title','Viden')
@section('content')
<div class="page-head"><div><div class="eyebrow">DET FÆLLES BIBLIOTEK</div><h1>{{ $folder ? $folders->firstWhere('id',$folder)?->name : 'Viden til hverdagen' }}</h1><p>Find vejledninger, håndbog og dokumenter til din arbejdsdag.</p></div>@if(auth()->user()->is_admin)<div class="actions"><a class="btn" href="{{ route('knowledge.create',['type'=>'pdf','mappe'=>$folder]) }}">＋ Upload PDF</a><a class="btn secondary" href="{{ route('knowledge.manage',['parent'=>$folder]) }}">Administrér bibliotek</a></div>@endif</div>
<nav class="knowledge-breadcrumb" aria-label="Bibliotekssti"><a href="{{ route('knowledge.index') }}">Viden</a>@foreach($trail as $ancestor)<span>/</span><a href="{{ route('knowledge.index',['mappe'=>$ancestor->id]) }}">{{ $ancestor->name }}</a>@endforeach</nav>
@if($folder)<p class="muted">Dokumenter og søgning omfatter også undermapper.</p>@if(auth()->user()->is_admin)<a class="btn secondary" href="{{ route('knowledge.manage',['parent'=>$folder]) }}">＋ Opret undermappe</a>@endif @endif
<form class="knowledge-search card" method="get" action="{{ route('knowledge.index') }}"><label class="search-query">Hvad leder du efter?<input type="search" name="q" value="{{ request('q') }}" maxlength="150" placeholder="Søg efter fx APV, instruktion eller et kaldenavn"></label><label>Hvor vil du søge?<select name="mappe"><option value="">Hele biblioteket</option>@foreach($folders as $item)<option value="{{ $item->id }}" @selected($folder==$item->id)>{{ $item->path }}</option>@endforeach</select></label><button type="submit" class="btn">Søg</button></form>
<div class="section-head"><h2>Mapper</h2>@if($folder)<a href="{{ route('knowledge.index') }}">Vis hele biblioteket ↗</a>@endif</div>
<div class="folder-grid">@forelse($children as $item)<a class="folder-card {{ $folder==$item->id ? 'active':'' }}" href="{{ route('knowledge.index',['mappe'=>$item->id]) }}"><svg width="34" height="30" viewBox="0 0 34 30" fill="none" aria-hidden="true"><path d="M2 7a3 3 0 0 1 3-3h8l4 4h12a3 3 0 0 1 3 3v13a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3Z" fill="currentColor" opacity=".18"/><path d="M2 11h30M2 7a3 3 0 0 1 3-3h8l4 4h12a3 3 0 0 1 3 3v13a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3Z" stroke="currentColor" stroke-width="1.5"/></svg><span><strong>{{ $item->name }}</strong><small>{{ $counts[$item->id] ?? 0 }} dokumenter direkte i mappen</small></span><span aria-hidden="true">↗</span></a>@empty<p class="muted">Ingen undermapper her endnu.</p>@endforelse</div>
<div class="section-head"><h2>{{ request('q') ? 'Søgeresultater':'Dokumenter og artikler' }}</h2><span class="muted">{{ $items->total() }} {{ $items->total()===1 ? 'resultat':'resultater' }}</span></div>
<div class="knowledge-results">@forelse($items as $item)<a class="card knowledge-item" href="{{ route('knowledge.show',$item->document_id) }}"><span class="file-type">{{ $item->type==='pdf' ? 'PDF':'ARTIKEL' }}</span><div><span class="eyebrow">{{ $folders->firstWhere('id',$item->folder_id)?->path }}</span><h3>{{ $item->title }}</h3><p>{{ $item->snippet }}</p><small>Version {{ $item->version }} · Publiceret {{ \App\Support\DateFormat::date($item->published_at) }}@if($item->page_count) · {{ $item->page_count }} sider @endif</small></div><span aria-hidden="true">↗</span></a>@empty<section class="card empty"><h3>{{ request('q') ? 'Ingen resultater':'Mappen er klar til indhold' }}</h3><p>{{ request('q') ? 'Prøv et andet søgeord eller vælg hele biblioteket.' : 'Publicerede artikler og PDF-filer vises her.' }}</p>@if(auth()->user()->is_admin)<a class="btn" href="{{ route('knowledge.create',['type'=>'pdf','mappe'=>$folder]) }}">Upload den første PDF</a>@endif</section>@endforelse</div>
@if($items->hasPages())<nav class="pagination actions" aria-label="Resultatsider">@if($items->previousPageUrl())<a class="btn secondary" href="{{ $items->previousPageUrl() }}">← Forrige</a>@endif<span>Side {{ $items->currentPage() }} af {{ $items->lastPage() }}</span>@if($items->nextPageUrl())<a class="btn secondary" href="{{ $items->nextPageUrl() }}">Næste →</a>@endif</nav>@endif
@endsection

