@extends('layout')
@section('title',$person->id===auth()->id() ? 'Min profil' : 'Medarbejderprofil')
@section('content')
@php($isAdmin=auth()->user()->canManageDevelopmentData())
<div class="page-head"><div class="profile-head"><div class="avatar">{{ mb_substr($person->name,0,1) }}</div><div><h1>{{ $person->name }}</h1><p class="muted">{{ $person->job_title ?: 'Stilling ikke angivet' }}</p></div></div>@if($isAdmin)<a class="btn secondary" href="/administration/medarbejder/{{ $person->id }}">Redigér medarbejder</a>@endif</div>
<nav class="actions" aria-label="Medarbejderprofil"><a class="btn" aria-current="page" href="/profil/{{ $person->id }}">Profil</a>@if($canSeeDevelopment)<a class="btn secondary" href="/profil/{{ $person->id }}?tab=kompetencer">Kompetencer</a>@endif</nav>
<div class="grid two"><section class="card"><h2>Kontakt og tilknytning</h2><dl class="detail-list"><div><dt>Mailadresse</dt><dd>{{ $person->email }}</dd></div><div><dt>Telefon</dt><dd>{{ $person->phone ?: 'Ikke angivet' }}</dd></div><div><dt>Leder</dt><dd>{{ $leaders->pluck('name')->join(', ') ?: 'Ingen leder tilknyttet' }}</dd></div></dl><div class="actions"><span class="pill {{ $person->active ? '':'inactive' }}">{{ $person->active ? 'Aktiv konto':'Deaktiveret' }}</span><span class="pill">Medarbejder</span>@if($person->is_leader)<span class="pill">Leder</span>@endif @if($person->is_admin)<span class="pill">Administrator</span>@endif</div></section>
<section class="card"><h2>Kompetencer og udvikling</h2>@if($canSeeDevelopment)<p class="muted">Privat kompetenceoverblik for medarbejderen, tildelte ledere og administratorer.</p><div class="actions"><a class="btn" href="/profil/{{ $person->id }}?tab=kompetencer">Se kompetencer ↗</a>@if($person->id===auth()->id() || auth()->user()->leads($person->id))<a class="btn secondary" href="/mus">MUS og opfølgning ↗</a>@endif</div>@else<p class="muted">Kompetencer, uddannelser, kørekort og certifikater er private. Du kan kun se dine egne oplysninger.</p>@endif<p class="muted">MUS er fortroligt mellem samtalens medarbejder og leder.</p></section></div>
<section class="card" style="margin-top:24px"><div class="section-head"><h2>Kommende ferie, kurser og skoleophold</h2><a href="{{ route('calendar.index',['user_id'=>$person->id]) }}">Se kalender</a></div>@forelse($upcoming as $entry)<p><strong>{{ \App\Http\Controllers\CalendarController::label($entry) }}</strong><br>{{ \App\Support\DateFormat::date($entry->starts_on) }} – {{ \App\Support\DateFormat::date($entry->ends_on) }}</p>@empty<p class="muted">Ingen kommende registreringer.</p>@endforelse</section>
<section class="card" style="margin-top:24px"><div class="section-head"><h2>Lånt fællesværktøj</h2><a href="{{ route('tools.index',['user_id'=>$person->id]) }}">Se værktøjsoversigt</a></div>@forelse($currentTools as $tool)<div class="info-row"><div><strong><a href="{{ route('tools.show',$tool->id) }}">{{ $tool->name }}</a></strong><p>{{ $tool->asset_number }} · {{ $tool->site ?: 'Byggeplads ikke angivet' }} · udlånt {{ \App\Support\DateFormat::dateTime($tool->checked_out_at) }}</p></div></div>@empty<p class="muted">Intet fællesværktøj er registreret på medarbejderen.</p>@endforelse</section>
@if($canSeeDevelopment)
<div class="section-head"><h2>Private referencefiler</h2><span class="muted" style="font-size:12px">Profilens ejer, tildelte ledere og administrator</span></div><section class="card">
@forelse($files as $file)<div class="info-row"><div><strong class="file-name">{{ $file->name }}</strong><p>PDF · {{ number_format($file->size/1024,0,',','.') }} KB · {{ \App\Support\DateFormat::dateTime($file->created_at) }}</p></div><a class="btn secondary small" href="/filer/{{ $file->id }}">Hent PDF</a></div>@empty<div class="empty"><h3>Ingen referencefiler endnu</h3><p>Administrator kan vedhæfte et kompetencekort som PDF.</p></div>@endforelse
@if($isAdmin)<form method="post" action="/profil/{{ $person->id }}/filer" enctype="multipart/form-data" style="margin-top:18px">@csrf<label>Tilføj en privat referencefil<input type="file" name="file" accept="application/pdf,.pdf" required><small>Kun PDF · højst 20 MB.</small></label><button type="submit" class="btn">Gem referencefil</button></form>@endif
</section>
@endif
@endsection
