@extends('layout')
@section('title',$version ? 'Redigér kladde':'Nyt indhold')
@section('content')
<div class="page-head"><div><div class="eyebrow">KONTORETS VIDENSBIBLIOTEK</div><h1>{{ $version ? 'Redigér kladde · version '.$version->version : 'Tilføj til biblioteket' }}</h1><p>Gem først en kladde. Kontrollér forhåndsvisningen, og publicér når indholdet er klar.</p></div><a class="btn secondary" href="{{ route('knowledge.manage') }}">Tilbage til biblioteket</a></div>
<form class="card knowledge-editor" id="knowledge-upload" method="post" enctype="multipart/form-data" action="{{ $version ? route('knowledge.save',[$version->document_id,$version->version]):route('knowledge.store') }}">@csrf
<input type="hidden" name="creation_token" value="{{ old('creation_token',\Illuminate\Support\Str::uuid()) }}">@if($version)<input type="hidden" name="revision" value="{{ old('revision',$version->revision) }}"><input type="hidden" name="document_revision" value="{{ old('document_revision',$document->revision) }}">@endif
<div class="form-grid"><label>Mappe<select name="folder_id" required><option value="">Vælg en mappe</option>@foreach($folders as $folder)<option value="{{ $folder->id }}" @selected(old('folder_id',$version?->folder_id ?? request('mappe'))==$folder->id)>{{ $folder->path }}</option>@endforeach</select></label><label>Indholdstype<select id="knowledge-type" name="type"><option value="pdf" @selected(old('type',$version?->type ?? request('type','pdf'))==='pdf')>PDF-fil</option><option value="article" @selected(old('type',$version?->type ?? request('type','pdf'))==='article')>Artikel</option></select></label></div>
@if($folders->isEmpty())<p class="notice">Opret først en mappe under <a href="{{ route('knowledge.manage') }}">Administrér bibliotek</a>.</p>@endif
<div id="pdf-upload-fields"><div class="upload-zone" id="upload-zone"><span class="upload-symbol" aria-hidden="true">↑</span><h2>{{ $file ? 'Upload en erstatningsfil':'Træk din PDF hertil' }}</h2><p>eller vælg den fra computeren · én PDF · højst 20 MB</p><label class="file-choice">Vælg PDF-fil<input id="knowledge-file" type="file" name="file" accept="application/pdf,.pdf"></label><p id="selected-file" role="status">{{ $file ? 'Nuværende fil: '.$file->name : 'Ingen fil valgt' }}</p></div>@if($file)<p class="muted">Den nuværende fil bevares, hvis du ikke vælger en ny.</p>@endif</div>
<label>Titel<input id="knowledge-title" name="title" value="{{ old('title',$version?->title) }}" maxlength="190" required placeholder="En kort titel, som kollegaerne kan genkende"></label>
<label>Kort beskrivelse<textarea name="description" required maxlength="1000" rows="3" placeholder="Hvad indeholder dokumentet, og hvornår er det nyttigt?">{{ old('description',$version?->description) }}</textarea></label>
<div id="article-fields"><label>Artikeltekst<textarea name="body" rows="15" maxlength="100000" placeholder="Skriv artiklen her. Afsnit og linjeskift bevares.">{{ old('body',$version?->body) }}</textarea></label><small>Teksten vises som almindelig tekst med dine linjeskift.</small></div>
<label>Søgeord og kaldenavne<input name="keywords" value="{{ old('keywords',$version?->keywords) }}" maxlength="1000" placeholder="Fx arbejdspladsvurdering, APV, instruktion"><small>Tilføj de ord, kollegaerne normalt søger efter. PDF-tekst indgår også, når den kan udtrækkes.</small></label>
<div class="form-grid"><label>Indholdsansvarlig<select name="responsible_id" required>@foreach($people as $person)<option value="{{ $person->id }}" @selected(old('responsible_id',$version?->responsible_id ?? auth()->id())==$person->id)>{{ $person->name }}</option>@endforeach</select></label><label>Næste gennemgang – valgfri<input type="date" name="review_on" value="{{ old('review_on',$version?->review_on) }}"></label></div>
<label>Hvad er ændret? – valgfri<textarea name="changes" maxlength="2000" rows="2" placeholder="Kort beskrivelse til versionshistorikken">{{ old('changes',$version?->changes) }}</textarea></label>
<div class="actions"><button type="submit" class="btn">Gem kladde og se forhåndsvisning</button><span class="muted">Kun administratorer kan se kladden.</span></div><p id="upload-progress" role="status" hidden>Uploader og klargør søgning. Store PDF-filer kan tage lidt tid…</p>
</form><script src="/knowledge-upload.js" defer></script>
@endsection

