@extends('layout')
@section('title','Administrér viden')
@section('content')
<div class="page-head"><div><div class="eyebrow">KONTORETS VIDENSBIBLIOTEK</div><h1>Indhold og mapper</h1><p>Tilføj filer, opdatér indhold og hold styr på den gældende version.</p></div><div class="actions"><a class="btn" href="{{ route('knowledge.create',['type'=>'pdf']) }}">＋ Upload PDF</a><a class="btn secondary" href="{{ route('knowledge.create',['type'=>'article']) }}">Skriv artikel</a></div></div>
<a href="{{ route('knowledge.index') }}">← Se medarbejdernes bibliotek</a>
<details class="card disclosure" @if($folders->isEmpty() || request()->has('parent')) open @endif><summary>Opret og navngiv mapper · {{ $folders->count() }}</summary><form method="post" action="{{ route('knowledge.folder') }}" class="folder-form">@csrf<label>Ny mappe<input name="name" maxlength="80" required placeholder="Fx APV eller Kemidokumentation"></label><label>Placering<select name="parent_id"><option value="">Øverste niveau</option>@foreach($folders as $parent)<option value="{{ $parent->id }}" @selected(old('parent_id',request('parent'))==$parent->id)>{{ $parent->path }}</option>@endforeach</select></label><button type="submit" class="btn">Opret mappe</button></form>@foreach($folders as $folder)<form method="post" action="{{ route('knowledge.folder',$folder->id) }}" class="folder-form">@csrf<input type="hidden" name="revision" value="{{ $folder->revision }}"><label>{{ $folder->path }}<input name="name" value="{{ $folder->name }}" maxlength="80" required aria-label="Mappenavn: {{ $folder->name }}"></label><button type="submit" class="btn secondary">Gem navn</button><a href="{{ route('knowledge.create',['type'=>'pdf','mappe'=>$folder->id]) }}">Upload til mappe ↗</a></form>@endforeach</details>
<div class="section-head"><h2>Alle dokumenter og kladder</h2></div><div class="knowledge-results">@forelse($documents as $document) @php($entries=$versions->get($document->id,collect())) @php($latest=$entries->first()) @php($current=$entries->firstWhere('id',$document->current_version_id)) @if($latest)<article class="card knowledge-item"><span class="file-type">{{ $latest->type==='pdf' ? 'PDF':'ARTIKEL' }}</span><div><h3><a href="{{ route('knowledge.version',[$document->id,$latest->version]) }}">{{ $latest->title }}</a></h3><p>{{ $folders->firstWhere('id',$latest->folder_id)?->path }} · Seneste: version {{ $latest->version }} · {{ $latest->status }}</p><small>{{ $current ? 'Medarbejderne ser version '.$current->version.' · '.$current->title:'Ingen publiceret version' }}</small>@if($current?->review_on && $current->review_on<now()->toDateString())<p class="review-due">Gennemgang forfalden {{ $current->review_on }}</p>@endif</div><a class="btn secondary small" href="{{ route('knowledge.version',[$document->id,$latest->version]) }}">Åbn</a></article>@endif @empty<div class="card empty"><h3>Biblioteket er klar</h3><p>Opret mapper og tilføj den første PDF eller artikel.</p></div>@endforelse</div>
@endsection

