@extends('layout')
@section('title',$version->title)
@section('content')
<nav class="knowledge-breadcrumb" aria-label="Bibliotekssti"><a href="{{ route('knowledge.index') }}">Viden</a>@foreach($trail as $ancestor)<span>/</span><a href="{{ route('knowledge.index',['mappe'=>$ancestor->id]) }}">{{ $ancestor->name }}</a>@endforeach</nav>
<div class="page-head"><div><div class="eyebrow">{{ $version->type==='pdf' ? 'PDF-DOKUMENT':'ARTIKEL' }} · VERSION {{ $version->version }}</div><h1>{{ $version->title }}</h1><p>{{ $version->description }}</p></div>@if($file)<a class="btn secondary" href="{{ route('knowledge.pdf',[$document->id,$version->version,'download'=>1]) }}">Hent PDF ↓</a>@endif</div>
@if($version->status!=='Publiceret')<p class="notice"><strong>{{ $version->status==='Kladde' ? 'Kladde · kun synlig for administratorer':'Historisk / arkiveret version · ikke gældende' }}</strong>@if($document->current_version_id)<br><a href="{{ route('knowledge.show',$document->id) }}">Åbn den gældende version ↗</a>@endif</p>@endif
<div class="document-meta"><span>Ansvarlig: {{ $responsible?->name }}</span><span>{{ $version->published_at ? 'Publiceret '.\App\Support\DateFormat::date($version->published_at):'Ikke publiceret' }}</span>@if($version->review_on)<span>Gennemgang: {{ \App\Support\DateFormat::date($version->review_on) }}</span>@endif</div>
@if(auth()->user()->is_admin)<div class="card publication-actions">@if($version->status==='Kladde')<p>Kontrollér indholdet herunder. Publicering gør denne version synlig for alle aktive medarbejdere.</p><div class="actions"><a class="btn secondary" href="{{ route('knowledge.edit',[$document->id,$version->version]) }}">Redigér kladde</a><form method="post" action="{{ route('knowledge.publish',[$document->id,$version->version]) }}">@csrf<input type="hidden" name="revision" value="{{ $version->revision }}"><input type="hidden" name="document_revision" value="{{ $document->revision }}"><button type="submit" class="btn">Publicér version {{ $version->version }}</button></form></div>@else<form method="post" action="{{ route('knowledge.newVersion',[$document->id,$version->version]) }}">@csrf<input type="hidden" name="document_revision" value="{{ $document->revision }}"><button type="submit" class="btn">＋ Opret ny version / udskift PDF</button></form>@endif
@if($version->type==='pdf')<p class="notice">{{ \App\Support\Knowledge::EXTRACTION[$version->pdf_text_status] ?? 'PDF-tekst ikke kontrolleret.' }}</p>@endif</div>@endif
@if($version->type==='pdf')<div id="knowledge-reader" data-url="{{ route('knowledge.pdf',[$document->id,$version->version]) }}"><p role="status">Starter PDF-læser…</p></div><noscript><p>PDF-læseren kræver JavaScript. Brug Hent PDF øverst.</p></noscript>@vite('resources/js/knowledge-reader.jsx')
@else<article class="card knowledge-article">{{ $version->body }}</article>@endif
@if($version->changes)<section class="card" style="margin-top:24px"><h2>Om denne version</h2><p class="preserve">{{ $version->changes }}</p></section>@endif
@if(auth()->user()->is_admin)<details class="card disclosure"><summary>Versionshistorik og arkivering</summary>@foreach($history as $entry)<div class="info-row"><div><a href="{{ route('knowledge.version',[$document->id,$entry->version]) }}">Version {{ $entry->version }} · {{ $entry->title }}</a><p>{{ $entry->status }} · {{ $entry->published_at ?: 'Ikke publiceret' }}</p></div></div>@endforeach @if($version->status!=='Arkiveret')<p class="muted">Arkivering skjuler denne version for medarbejderne. Indhold og historik bevares.</p><form method="post" action="{{ route('knowledge.archive',[$document->id,$version->version]) }}">@csrf<input type="hidden" name="document_revision" value="{{ $document->revision }}"><button type="submit" class="btn secondary">Arkivér denne version</button></form>@endif</details>@endif
@endsection

