<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\DevelopmentController;
use App\Http\Controllers\IntranetController;
use App\Http\Controllers\KlsController;
use App\Http\Controllers\KnowledgeController;
use App\Http\Controllers\MusController;
use App\Http\Controllers\ProfileCertificateController;
use App\Http\Controllers\ToolController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth')->get('/foerste-login', [\App\Http\Controllers\FirstPasswordController::class, 'edit'])->name('password.first');
Route::middleware(['auth', 'throttle:5,1'])->post('/foerste-login', [\App\Http\Controllers\FirstPasswordController::class, 'update'])->name('password.first.update');

Route::view('/forgot-password', 'auth.forgot')->name('password.request');
Route::middleware('auth')->get('/sikkerhed', fn () => view('auth.security'));
Route::middleware('auth')->group(function () {
    Route::get('/vaerktoej', [ToolController::class, 'index'])->name('tools.index');
    Route::get('/vaerktoej/opret', [ToolController::class, 'edit'])->name('tools.edit');
    Route::get('/vaerktoej/{id}/rediger', [ToolController::class, 'edit'])->whereNumber('id')->name('tools.edit.existing');
    Route::post('/vaerktoej/{id?}', [ToolController::class, 'save'])->whereNumber('id')->name('tools.save');
    Route::get('/vaerktoej/{id}', [ToolController::class, 'show'])->whereNumber('id')->name('tools.show');
    Route::post('/vaerktoej/{id}/udlaan', [ToolController::class, 'checkout'])->whereNumber('id')->name('tools.checkout');
    Route::post('/vaerktoej/{id}/retur', [ToolController::class, 'returnTool'])->whereNumber('id')->name('tools.return');
    Route::get('/kalender', [CalendarController::class, 'index'])->name('calendar.index');
    Route::get('/kalender/registrering/{id?}', [CalendarController::class, 'edit'])->whereNumber('id')->name('calendar.edit');
    Route::post('/kalender/registrering/{id?}', [CalendarController::class, 'save'])->whereNumber('id')->name('calendar.save');
    Route::post('/kalender/{id}/aflys', [CalendarController::class, 'cancel'])->whereNumber('id')->name('calendar.cancel');
    Route::post('/profil/{id}/certificering', [ProfileCertificateController::class, 'save'])->whereNumber('id')->name('profile.certificate.save');
    Route::post('/profil/{id}/certificering/{link}/fjern', [ProfileCertificateController::class, 'unlink'])->whereNumber(['id', 'link'])->name('profile.certificate.unlink');
    Route::get('/kompetencekort/{id}', [KlsController::class, 'card'])->whereNumber('id')->name('development.card');
    Route::post('/kompetencekort/{id}/vurdering', [DevelopmentController::class, 'assess'])->whereNumber('id')->name('development.assess');
    Route::post('/kompetencekort/{id}/grunduddannelse', [DevelopmentController::class, 'educationSave'])->whereNumber('id')->name('development.education.save');
    Route::post('/kompetencekort/{id}/grunduddannelse/{education}/slet', [DevelopmentController::class, 'educationDelete'])->whereNumber(['id', 'education'])->name('development.education.delete');
    Route::post('/kompetencekort/{id}/koerekort', [DevelopmentController::class, 'licenseSave'])->whereNumber('id')->name('development.license.save');
    Route::post('/kompetencekort/{id}/koerekort/{license}/slet', [DevelopmentController::class, 'licenseDelete'])->whereNumber(['id', 'license'])->name('development.license.delete');
    Route::post('/kompetencekort/{id}/certifikat', [DevelopmentController::class, 'safetyCertificateSave'])->whereNumber('id')->name('development.safety.save');
    Route::post('/kompetencekort/{id}/certifikat/{certificate}/slet', [DevelopmentController::class, 'safetyCertificateDelete'])->whereNumber(['id', 'certificate'])->name('development.safety.delete');
    Route::post('/kompetencekort/{id}/certifikat-link', [DevelopmentController::class, 'certificateLinkSave'])->whereNumber('id')->name('development.certificate-link.save');
    Route::post('/kompetencekort/{id}/certifikat-link/{link}/slet', [DevelopmentController::class, 'certificateLinkDelete'])->whereNumber(['id', 'link'])->name('development.certificate-link.delete');
    Route::post('/kompetencekort/{id}/baggrund', [DevelopmentController::class, 'entry'])->whereNumber('id')->name('development.entry');
    Route::post('/kompetencekort/{id}/gennemgang', [DevelopmentController::class, 'review'])->whereNumber('id')->name('development.review');
    Route::get('/kompetencekort/{id}/kursus/{record?}', [DevelopmentController::class, 'courseForm'])->whereNumber(['id', 'record'])->name('development.course');
    Route::post('/kompetencekort/{id}/kursus/{record?}', [DevelopmentController::class, 'courseSave'])->whereNumber(['id', 'record'])->name('development.course.save');
    Route::get('/kompetencer', [KlsController::class, 'matrix'])->name('development.matrix');
    Route::get('/kompetencer.csv', [KlsController::class, 'matrix'])->name('competencies.export');
    Route::get('/kls/matrix', [KlsController::class, 'matrix'])->name('kls.matrix');
    Route::get('/kls/kort/{id}', [KlsController::class, 'card'])->name('kls.card');
    Route::post('/kls/kort/{id}', [KlsController::class, 'save'])->name('kls.save');
    Route::post('/kls/skill', [KlsController::class, 'skill'])->name('kls.skill');
    Route::get('/katalog', [DevelopmentController::class, 'catalog'])->name('development.catalog');
    Route::post('/katalog', [DevelopmentController::class, 'catalogSave'])->name('development.catalog.save');
    Route::get('/mus', [MusController::class, 'index'])->name('mus.index');
    Route::post('/mus', [MusController::class, 'create'])->name('mus.create');
    Route::get('/mus/{id}', [MusController::class, 'show'])->whereNumber('id')->name('mus.show');
    Route::post('/mus/{id}/gem', [MusController::class, 'save'])->whereNumber('id')->name('mus.save');
    Route::post('/mus/{id}/del', [MusController::class, 'share'])->whereNumber('id')->name('mus.share');
    Route::post('/mus/{id}/klargoer', [MusController::class, 'publish'])->whereNumber('id')->name('mus.publish');
    Route::post('/mus/{id}/bekraeft', [MusController::class, 'confirm'])->whereNumber('id')->name('mus.confirm');
    Route::post('/mus/{id}/opfoelgning/{followup}', [MusController::class, 'followup'])->whereNumber(['id', 'followup'])->name('mus.followup');
    Route::post('/mus/{id}/arkiver', [MusController::class, 'archive'])->whereNumber('id')->name('mus.archive');
    Route::get('/mus/{id}/udskriv/{version}', [MusController::class, 'print'])->whereNumber(['id', 'version'])->name('mus.print');
    Route::get('/', [IntranetController::class, 'home']);
    Route::get('/viden', [KnowledgeController::class, 'index'])->name('knowledge.index');
    Route::get('/viden/administration', [KnowledgeController::class, 'manage'])->name('knowledge.manage');
    Route::post('/viden/mappe/{id?}', [KnowledgeController::class, 'folder'])->whereNumber('id')->name('knowledge.folder');
    Route::get('/viden/nyt', [KnowledgeController::class, 'edit'])->name('knowledge.create');
    Route::post('/viden/nyt', [KnowledgeController::class, 'save'])->name('knowledge.store');
    Route::get('/viden/{id}', [KnowledgeController::class, 'show'])->whereNumber('id')->name('knowledge.show');
    Route::get('/viden/{id}/version/{number}', [KnowledgeController::class, 'show'])->whereNumber(['id', 'number'])->name('knowledge.version');
    Route::get('/viden/{id}/version/{number}/rediger', [KnowledgeController::class, 'edit'])->whereNumber(['id', 'number'])->name('knowledge.edit');
    Route::post('/viden/{id}/version/{number}/gem', [KnowledgeController::class, 'save'])->whereNumber(['id', 'number'])->name('knowledge.save');
    Route::post('/viden/{id}/version/{number}/publicer', [KnowledgeController::class, 'publish'])->whereNumber(['id', 'number'])->name('knowledge.publish');
    Route::post('/viden/{id}/version/{number}/ny', [KnowledgeController::class, 'newVersion'])->whereNumber(['id', 'number'])->name('knowledge.newVersion');
    Route::post('/viden/{id}/version/{number}/arkiver', [KnowledgeController::class, 'archive'])->whereNumber(['id', 'number'])->name('knowledge.archive');
    Route::get('/viden/{id}/version/{number}/pdf', [KnowledgeController::class, 'pdf'])->whereNumber(['id', 'number'])->name('knowledge.pdf');
    Route::get('/kollegaer', [IntranetController::class, 'colleagues']);
    Route::get('/profil/{id?}', [IntranetController::class, 'profile'])->whereNumber('id');
    Route::get('/mit-team', [IntranetController::class, 'team']);
    Route::post('/profil/{id}/filer', [IntranetController::class, 'upload'])->whereNumber('id');
    Route::get('/filer/{id}', [IntranetController::class, 'download'])->whereNumber('id');
    Route::get('/administration', [AdminController::class, 'index']);
    Route::get('/administration/adgang.csv', [AdminController::class, 'export']);
    Route::get('/administration/medarbejder/{id?}', [AdminController::class, 'edit'])->whereNumber('id');
    Route::post('/administration/medarbejder/{id?}', [AdminController::class, 'save'])->whereNumber('id');
    Route::post('/administration/medarbejder/{id}/adgangskode', [AdminController::class, 'resetPassword'])->whereNumber('id')->middleware('throttle:5,1');
});
