@extends('layout')
@section('title','Fællesværktøj')
@section('content')
<link rel="stylesheet" href="/tools.css?v=20260917-2">
<div class="page-head"><div><div class="eyebrow">UDSTYRSOVERBLIK</div><h1>Fællesværktøj</h1><p>Se hvem der har værktøjet, og hvilken byggeplads det befinder sig på.</p></div>@if(auth()->user()->is_admin)<a class="btn" href="{{ route('tools.edit') }}">＋ Opret værktøj</a>@endif</div>
<form class="card filters tool-filters" method="get"><label>Søg<input name="q" value="{{ request('q') }}" placeholder="Nummer, navn, medarbejder eller byggeplads"></label><label>Status<select name="status"><option value="">Aktivt værktøj</option><option value="available" @selected(request('status')==='available')>På lager</option><option value="loaned" @selected(request('status')==='loaned')>Udlånt</option><option value="inactive" @selected(request('status')==='inactive')>Deaktiveret</option></select></label><label>Medarbejder<select name="user_id"><option value="">Alle medarbejdere</option>@foreach($people as $person)<option value="{{ $person->id }}" @selected((string)request('user_id')===(string)$person->id)>{{ $person->name }}</option>@endforeach</select></label><button class="btn secondary">Vis</button></form>
<div class="section-head"><h2>Værktøjsliste</h2><span class="muted">{{ $tools->count() }} stk.</span></div>
@php($sortLink=function($field){$next=request('sort')===$field && request('direction','asc')==='asc'?'desc':'asc';return route('tools.index',array_merge(request()->only(['q','status','user_id']),['sort'=>$field,'direction'=>$next]));})
<div class="table-wrap"><table><thead><tr><th><a href="{{ $sortLink('asset_number') }}">Fællesnr. ↕</a></th><th><a href="{{ $sortLink('name') }}">Værktøj ↕</a></th><th><a href="{{ $sortLink('category') }}">Kategori ↕</a></th><th><a href="{{ $sortLink('status') }}">Status ↕</a></th><th>Placering</th><th>Udlånt</th><th></th></tr></thead><tbody>
@forelse($tools as $tool)<tr><td><strong>{{ $tool->asset_number }}</strong></td><td><a class="person-name" href="{{ route('tools.show',$tool->id) }}">{{ $tool->name }}</a><small>@if($tool->manufacturer || $tool->model){{ trim($tool->manufacturer.' '.$tool->model) }}@endif</small>@if($tool->serial_numbers->isNotEmpty())<small>{{ $tool->serial_numbers->pluck('serial_number')->join(' · ') }}</small>@endif</td><td>{{ $tool->category ?: '—' }}<small>{{ $tool->is_fleet ? 'Fleet' : ($tool->is_leased ? 'Leaset':'Ejet') }}</small></td><td><span class="pill {{ $tool->loan_id ? 'waiting':'' }}">{{ !$tool->active ? 'Deaktiveret' : ($tool->loan_id ? 'Udlånt':'På lager') }}</span></td><td>@if($tool->loan_id)<a href="/profil/{{ $tool->user_id }}">{{ $tool->employee_name }}</a><small>{{ $tool->site ?: 'Byggeplads ikke angivet' }}</small>@else — @endif</td><td>{{ $tool->checked_out_at ? \App\Support\DateFormat::dateTime($tool->checked_out_at) : '—' }}</td><td><div class="actions"><a class="btn secondary small" href="{{ route('tools.show',$tool->id) }}">Se</a>@if(auth()->user()->is_admin)<a class="btn secondary small" href="{{ route('tools.edit.existing',$tool->id) }}">Rediger</a>@endif</div></td></tr>
@empty<tr><td colspan="7"><div class="empty"><h3>Ingen værktøjer fundet</h3><p>Administrator kan oprette det første værktøj.</p></div></td></tr>@endforelse
</tbody></table></div>
@endsection
