@extends('layout')
@section('title',$tool->name)
@section('content')
<link rel="stylesheet" href="/tools.css?v=20260917-2">
<div class="page-head"><div><div class="eyebrow">{{ $tool->asset_number }}</div><h1>{{ $tool->name }}</h1><p>{{ collect([$tool->category,$tool->manufacturer,$tool->model])->filter()->join(' · ') ?: 'Ingen yderligere oplysninger' }}</p></div><div class="actions"><a class="btn secondary" href="{{ route('tools.index') }}">Tilbage</a>@if(auth()->user()->is_admin)<a class="btn" href="{{ route('tools.edit.existing',$tool->id) }}">Rediger</a>@endif</div></div>
<div class="grid two"><section class="card"><h2>Status</h2>@if($current)<p><span class="pill waiting">Udlånt</span></p><dl class="detail-list"><div><dt>Medarbejder</dt><dd><a href="/profil/{{ $current->user_id }}">{{ $current->employee_name }}</a></dd></div><div><dt>Byggeplads</dt><dd>{{ $current->site ?: 'Ikke angivet' }}</dd></div><div><dt>Udlånt</dt><dd>{{ \App\Support\DateFormat::dateTime($current->checked_out_at) }}</dd></div></dl>@if($current->checkout_note)<p>{{ $current->checkout_note }}</p>@endif
@if(auth()->user()->is_admin)<form method="post" action="{{ route('tools.return',$tool->id) }}">@csrf<label>Note ved retur (valgfri)<textarea name="return_note" maxlength="2000"></textarea></label><button class="btn">Registrer retur nu</button></form>@endif
@else<p><span class="pill">På lager</span></p>@if(auth()->user()->is_admin && $tool->active)<form method="post" action="{{ route('tools.checkout',$tool->id) }}">@csrf<label>Medarbejder<select name="user_id" required><option value="">Vælg medarbejder</option>@foreach($people as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></label><label>Byggeplads (valgfri)<input name="site" maxlength="190" placeholder="Fx Byggeplads Sønderborg"></label><label>Note (valgfri)<textarea name="checkout_note" maxlength="2000"></textarea></label><button class="btn">Registrer udlån nu</button></form>@endif @endif</section>
<section class="card"><h2>Stamdata</h2><dl class="detail-list"><div><dt>Fællesnummer</dt><dd>{{ $tool->asset_number }}</dd></div><div><dt>Ejerskab</dt><dd>{{ $tool->is_fleet ? 'Fleet hos Hilti' : ($tool->is_leased ? 'Leaset':'Ejet') }}</dd></div><div><dt>Kategori</dt><dd>{{ $tool->category ?: '—' }}</dd></div><div><dt>Status i register</dt><dd>{{ $tool->active ? 'Aktiv':'Deaktiveret' }}</dd></div></dl><h3>Serienumre</h3>@forelse($serialNumbers as $serial)<span class="serial-number">{{ $serial }}</span>@empty<p class="muted">Ingen serienumre registreret.</p>@endforelse @if($tool->note)<p>{{ $tool->note }}</p>@endif</section></div>
<div class="section-head"><h2>Udlånshistorik</h2><span class="muted">{{ $history->count() }} registreringer</span></div><div class="table-wrap"><table><thead><tr><th>Medarbejder</th><th>Byggeplads</th><th>Udlånt</th><th>Retur</th><th>Registreret af</th></tr></thead><tbody>@forelse($history as $loan)<tr><td><a href="/profil/{{ $loan->user_id }}">{{ $loan->employee_name }}</a></td><td>{{ $loan->site ?: '—' }}</td><td>{{ \App\Support\DateFormat::dateTime($loan->checked_out_at) }}<small>{{ $loan->checkout_note }}</small></td><td>{{ $loan->returned_at ? \App\Support\DateFormat::dateTime($loan->returned_at) : 'Ikke returneret' }}<small>{{ $loan->return_note }}</small></td><td>{{ $loan->checkout_admin_name }}@if($loan->return_admin_name)<small>Retur: {{ $loan->return_admin_name }}</small>@endif</td></tr>@empty<tr><td colspan="5"><div class="empty">Ingen udlån endnu.</div></td></tr>@endforelse</tbody></table></div>
@endsection
