@extends('layout')
@section('title','Kompetencekort')
@section('content')
@php($isAdmin=auth()->user()->canManageDevelopmentData())
<div class="page-head"><div><div class="eyebrow">FAGLIGHED OG UDVIKLING</div><h1>{{ $person->name }}</h1><p>Kompetencekort · {{ $person->job_title ?: 'Stilling ikke angivet' }}</p></div><div class="actions"><a class="btn secondary" href="/profil/{{ $person->id }}">Profil</a>@if($isAdmin)<a class="btn" href="{{ route('development.course',$person->id) }}">＋ Registrér kursus</a>@endif</div></div>
<div class="notice">Kompetencer, uddannelser, kørekort og certifikater vises kun for medarbejderen selv, tildelte ledere og KLS-administratorer. Kun administratorer kan ændre data.</div>

<div class="section-head"><h2>Faglige kompetencer</h2>@if(auth()->user()->is_admin || auth()->user()->is_leader)<a href="{{ route('development.matrix') }}">Se kompetencematrix ↗</a>@endif</div>
<div class="table-wrap"><table><thead><tr><th>Kompetence</th><th>Aktuelt niveau</th><th>Senest vurderet</th><th>Ansvarlig</th><th>Tilknyttede certificeringer</th></tr></thead><tbody>@foreach($competencies as $competency) @php($assessment=$assessments->get($competency->id))<tr><td>{{ $competency->name }}</td><td><span class="pill {{ !$assessment || $assessment->level===1 ? 'inactive':'' }}">{{ $levels[$assessment->level ?? 1] }}</span></td><td>{{ $assessment ? \App\Support\DateFormat::date($assessment->assessed_on):'—' }}</td><td>{{ $assessment ? ($people[$assessment->assessor_id] ?? 'Ukendt'):'—' }}</td><td>@forelse($certificateLinks->where('competency_id',$competency->id) as $link)<span class="pill">{{ $link->certificate_title }}</span>@empty<span class="muted">—</span>@endforelse</td></tr>@endforeach</tbody></table></div>
@if($isAdmin)
<details class="card disclosure"><summary>Registrér en ny faglig vurdering</summary><form method="post" action="{{ route('development.assess',$person->id) }}">@csrf<input type="hidden" name="submission_id" value="{{ \Illuminate\Support\Str::uuid() }}"><div class="form-grid"><label>Kompetence<select name="competency_id" required>@foreach($competencies as $competency)<option value="{{ $competency->id }}">{{ $competency->name }}</option>@endforeach</select></label><label>Niveau<select name="level">@foreach($levels as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label>Vurderingsdato<input name="assessed_on" type="date" value="{{ now()->toDateString() }}" max="{{ now()->toDateString() }}" required></label><label>Grundlag for vurderingen<textarea name="basis" required maxlength="2000" placeholder="Hvilken konkret opgave eller observation ligger til grund?"></textarea></label></div><label class="check"><input type="checkbox" name="visible_to_colleagues" value="1">Må vises som hjælpekompetence ved selvstændigt niveau eller højere</label><button type="submit" class="btn">Registrér faglig vurdering</button></form></details>
<details class="card disclosure"><summary>Tilføj ny faglig kompetence til listen</summary><form method="post" action="{{ route('development.catalog.save') }}">@csrf<input type="hidden" name="kind" value="competencies"><label>Kompetencenavn<input name="name" required maxlength="190"></label><button type="submit" class="btn">Tilføj kompetence</button></form></details>
@endif

<div class="section-head"><h2>Uddannelse og certifikater</h2><span class="muted" style="font-size:12px">Tre adskilte datastrukturer</span></div>
<div class="grid three">
<section class="card"><h2>Grunduddannelser</h2>@forelse($educations as $education)<div class="info-row"><strong>{{ $education->title }}</strong>@if($isAdmin)<form method="post" action="{{ route('development.education.delete',[$person->id,$education->id]) }}">@csrf<button class="btn secondary small" type="submit">Slet</button></form>@endif</div>@empty<p class="muted">Ingen grunduddannelser registreret.</p>@endforelse @if($isAdmin)<form method="post" action="{{ route('development.education.save',$person->id) }}">@csrf<label>Tilføj grunduddannelse<select name="title" required>@foreach($educationOptions as $option)<option value="{{ $option }}">{{ $option }}</option>@endforeach</select></label><button type="submit" class="btn">Tilføj</button></form>@endif</section>
<section class="card"><h2>Kørekort</h2>@forelse($licenses as $license)<div class="info-row"><div><strong>Kørekort {{ $license->category }}</strong><p><span class="expiry {{ \App\Support\Development::expiryStatus($license->expires_on) }}">{{ \App\Support\Development::expiryLabel($license->expires_on) }}</span></p></div>@if($isAdmin)<form method="post" action="{{ route('development.license.delete',[$person->id,$license->id]) }}">@csrf<button class="btn secondary small" type="submit">Slet</button></form>@endif</div>@empty<p class="muted">Ingen kørekort registreret.</p>@endforelse @if($isAdmin)<form method="post" action="{{ route('development.license.save',$person->id) }}">@csrf<div class="form-grid"><label>Kategori<input name="category" maxlength="20" required placeholder="B, BE, C"></label><label>Udløbsdato<input name="expires_on" type="date" required></label></div><button type="submit" class="btn">Gem kørekort</button></form>@endif</section>
<section class="card"><h2>Sikkerheds- og maskincertifikater</h2>@forelse($safetyCertificates as $certificate)<div class="info-row"><div><strong>{{ $certificate->title }}</strong><p><span class="expiry {{ \App\Support\Development::expiryStatus($certificate->expires_on) }}">{{ \App\Support\Development::expiryLabel($certificate->expires_on) }}</span></p></div>@if($isAdmin)<form method="post" action="{{ route('development.safety.delete',[$person->id,$certificate->id]) }}">@csrf<button class="btn secondary small" type="submit">Slet</button></form>@endif</div>@empty<p class="muted">Ingen certifikater registreret.</p>@endforelse @if($isAdmin)<form method="post" action="{{ route('development.safety.save',$person->id) }}">@csrf<label>Certifikat<select name="title" required>@foreach($safetyOptions as $option)<option value="{{ $option }}">{{ $option }}</option>@endforeach</select></label><label>Udløbsdato<input name="expires_on" type="date" required></label><button type="submit" class="btn">Gem certifikat</button></form>@endif</section>
</div>

<div class="section-head"><h2>Tilknyttede certificeringer</h2></div>
<section class="card">@forelse($certificateLinks as $link)<div class="info-row"><div><strong>{{ $link->competency_name }}</strong><p>{{ $link->certificate_title }} · {{ \App\Support\Development::expiryLabel($link->expires_on) }}</p></div>@if($isAdmin)<form method="post" action="{{ route('development.certificate-link.delete',[$person->id,$link->id]) }}">@csrf<button class="btn secondary small" type="submit">Slet</button></form>@endif</div>@empty<p class="muted">Ingen certifikater er knyttet til faglige kompetencer endnu.</p>@endforelse @if($isAdmin)<form method="post" action="{{ route('development.certificate-link.save',$person->id) }}">@csrf<div class="form-grid"><label>Kompetence<select name="competency_id" required>@foreach($competencies as $competency)<option value="{{ $competency->id }}">{{ $competency->name }}</option>@endforeach</select></label><label>Certifikat<select name="certificate" required>@foreach($certificateOptions as $option)<option value="{{ $option->value }}">{{ $option->label }}</option>@endforeach</select></label></div><button type="submit" class="btn">Knyt certifikat til kompetence</button></form>@endif</section>

<div class="section-head"><h2>Kurser og historik</h2><span class="muted">{{ $records->count() }} registreringer</span></div>
@forelse($records->groupBy(fn($r)=>$r->course_id ? 'course-'.$r->course_id : 'topic-'.mb_strtolower($r->topic)) as $group)
<section class="card course-group"><h3>{{ $group->first()->topic }}</h3>
@php($dated=$group->where('status','Gennemført')->filter(fn($r)=>$r->date_precision==='date' && $r->completed_on)->sortByDesc('completed_on')->first())
<p class="muted">{{ $dated ? 'Senest gennemført med præcis dato: '.\App\Support\Development::courseDate($dated) : 'Ingen gennemførelse med præcis dato registreret' }}@if($group->where('status','Gennemført')->where('date_precision','!=','date')->count()) · Se også historiske år/perioder nedenfor.@endif</p>
@foreach($group as $record)<div class="course-row"><div><span class="pill">{{ $record->status }}</span><p>{{ $record->status==='Gennemført' ? \App\Support\Development::courseDate($record) : ($record->planned_on ? 'Planlagt: '.\App\Support\DateFormat::date($record->planned_on):'Dato ikke fastlagt') }}</p><small>{{ $record->provider }}</small></div><div><strong>{{ \App\Support\Development::validity($record) }}</strong><p class="muted">Genopfriskning: {{ $record->refresh_on ? \App\Support\DateFormat::date($record->refresh_on):'Ikke aftalt' }}</p>@if($record->note && (auth()->user()->is_admin || auth()->id()===$person->id))<p class="private-note">{{ $record->note }}</p>@endif</div><div class="actions">@if($record->certificate_id)<a class="btn secondary small" href="/filer/{{ $record->certificate_id }}">Kursusbevis ↓</a>@endif @if($isAdmin)<a class="btn secondary small" href="{{ route('development.course',[$person->id,$record->id]) }}">Opdatér</a>@endif</div></div>@if($transfers->has($record->id))<details class="disclosure"><summary>Aftalt fagligt grundlag fra MUS</summary>@foreach($transfers[$record->id] as $transfer) @php($projection=\App\Support\MusWorkflow::decode($transfer->projection))<h4>Version {{ $transfer->version }} · {{ $projection['result'] }}</h4><p class="preserve">{{ $projection['description'] }}</p><p>Frist: {{ $projection['deadline'] }}</p>@endforeach</details>@endif @endforeach</section>
@empty<div class="card empty"><h3>Ingen kurser registreret</h3><p>KLS kan oprette behov, planer og gennemførte kurser. Gentagelser registreres som nye deltagelser.</p></div>@endforelse

<div class="section-head"><h2>Aftalte udviklingsmål fra MUS</h2></div><div class="card">@forelse($goals as $goal)<div class="info-row"><div><h3>{{ $competencies->firstWhere('id',$goal->competency_id)?->name ?? 'Udviklingsmål' }}</h3><p class="preserve">{{ $goal->description }}</p><small>Frist {{ \App\Support\DateFormat::date($goal->deadline) }} · Ønsket niveau: {{ $levels[$goal->desired_level] ?? 'Ikke angivet' }} · Kilde: MUS, version {{ $goal->source_version }}</small></div><span class="pill">{{ $goal->status }}</span></div>@empty<p class="muted">Ingen bekræftede udviklingsmål overført endnu.</p>@endforelse</div>
<div class="grid two" style="margin-top:24px">@foreach(['education'=>'Uddannelse / historik','experience'=>'Erhvervserfaring'] as $type=>$label)<section class="card"><h2>{{ $label }}</h2>@forelse($entries->where('type',$type) as $entry)<div class="info-row"><div><h3>{{ $entry->title }}</h3><p>{{ $entry->period }} · {{ $entry->description }}</p></div></div>@empty<p class="muted">Ingen oplysninger registreret.</p>@endforelse</section>@endforeach</div>
@if($isAdmin)<details class="card disclosure"><summary>Tilføj historisk uddannelse eller erhvervserfaring</summary><form method="post" action="{{ route('development.entry',$person->id) }}">@csrf<input type="hidden" name="submission_id" value="{{ \Illuminate\Support\Str::uuid() }}"><div class="form-grid"><label>Type<select name="type"><option value="education">Uddannelse / historik</option><option value="experience">Erhvervserfaring</option></select></label><label>Uddannelse / virksomhed<input name="title" required maxlength="190"></label><label>År eller periode<input name="period" maxlength="100" placeholder="Eksempelvis 2006–2008"></label><label>Funktion eller beskrivelse<input name="description" maxlength="1000"></label></div><button type="submit" class="btn">Gem oplysning</button></form></details>@endif
<section class="card" style="margin-top:24px"><h2>Gennemgang af kompetencekort</h2><p class="muted">{{ $person->competency_reviewed_on ? 'Senest gennemgået '.\App\Support\DateFormat::date($person->competency_reviewed_on).' af '.($people[$person->competency_reviewed_by] ?? ''):'Endnu ikke gennemgået' }}</p>@if($isAdmin)<form method="post" action="{{ route('development.review',$person->id) }}" class="actions">@csrf<label>Gennemgangsdato<input name="reviewed_on" type="date" required value="{{ now()->toDateString() }}"></label><button type="submit" class="btn secondary">Registrér gennemgang</button></form>@endif</section>
<details class="card disclosure"><summary>Tidligere faglige vurderinger</summary>@forelse($assessmentHistory as $entry)<div class="info-row"><div><strong>{{ $competencies->firstWhere('id',$entry->competency_id)?->name }} · {{ $levels[$entry->level] }}</strong><p>{{ \App\Support\DateFormat::date($entry->assessed_on) }} · {{ $people[$entry->assessor_id] ?? '' }}</p><p>{{ $entry->basis }}</p></div></div>@empty<p class="muted">Ingen vurderinger endnu.</p>@endforelse</details>
@endsection
