@extends('layout')
@section('title','Kompetencematrix')
@section('content')
<div class="page-head"><div><div class="eyebrow">KOMPETENCER</div><h1>Kompetencematrix</h1><p>Vælg én kategori ad gangen, og brug filtrene til at finde de relevante medarbejdere.</p></div></div>
<p><a class="btn secondary" href="{{ route('competencies.export',request()->only(['q','category','role'])) }}">Hent udvalg som CSV</a></p>
<form class="card kls-filters" method="get"><label>Søg medarbejder<input type="search" name="q" value="{{ request('q') }}" placeholder="Skriv et navn" maxlength="100"></label><label>Stillingsbetegnelse<select name="role"><option value="">Alle stillinger</option>@foreach(\App\Models\User::JOB_ROLES as $role)<option value="{{ $role }}" @selected(request('role')===$role)>{{ $role }}</option>@endforeach</select></label><label>Kategori<select name="category">@foreach($categories as $category)<option value="{{ $category }}" @selected($selectedCategory===$category)>{{ $category }}</option>@endforeach</select></label><div class="actions"><button class="btn" type="submit">Vis udvalg</button><a class="btn secondary" href="{{ route('kls.matrix') }}">Nulstil</a></div></form>
<nav class="category-tabs" aria-label="Kompetencekategori">@foreach($categories as $category)<a class="{{ $selectedCategory===$category ? 'selected':'' }}" href="{{ route('kls.matrix',array_merge(request()->only(['q','role']),['category'=>$category])) }}">{{ $category }}</a>@endforeach</nav>
<div class="kls-overview"><div><strong>{{ $people->count() }}</strong><span>medarbejdere i visningen</span></div><div><strong>{{ $visibleSkills->count() }}</strong><span>punkter i kategorien</span></div><div><strong>{{ $records->filter(fn($record)=>$record->expires_on && $record->expires_on < now()->toDateString())->count() }}</strong><span>udløbne registreringer</span></div></div>
<div class="section-head"><div><div class="eyebrow">VALGT KATEGORI</div><h2>{{ $selectedCategory ?: 'Ingen kategori' }}</h2></div></div>
<div class="table-wrap kls-table-wrap"><table class="kls-matrix"><thead><tr><th>Medarbejder</th>@foreach($visibleSkills as $skill)<th>{{ $skill->name }}</th>@endforeach</tr></thead><tbody>@forelse($people as $person)<tr><td><a href="/profil/{{ $person->id }}?tab=kompetencer"><span class="person-name">{{ $person->name }}</span><small>{{ $person->jobRolesLabel() }}</small></a></td>@foreach($visibleSkills as $skill) @php($record=$records->get($person->id.':'.$skill->id))<td class="kls-value-cell">@if(!$record)<span class="kls-value empty-value">—</span>@elseif($skill->kind==='boolean')<span class="kls-value {{ $record->value ? 'yes':'no' }}">{{ $record->value ? '✓':'–' }}</span>@else<span class="kls-value level-value level-{{ $record->value }}">{{ $record->value }}</span>@endif</td>@endforeach</tr>@empty<tr><td colspan="{{ $visibleSkills->count()+1 }}">Ingen medarbejdere fundet.</td></tr>@endforelse</tbody></table></div>
<p class="matrix-legend"><span><i class="kls-value yes">✓</i> Ja</span><span><i class="kls-value no">–</i> Nej / ikke gældende</span><span><i class="kls-value empty-value">—</i> Ikke registreret</span></p>
@include('development.kls-scale')
@endsection
